### PR TITLE
Fix for calling Exception from within a namespace

### PR DESCRIPTION
**Pull request by Samyoul**
Calling the Exception class from within a namespace has php assuming Exception is a class belonging to the namespace, can be fixed by prepending the class name with "\".

### CODE REVIEW

**Comment by Samyoul** [comment]
This class assumes that the command line will be ran on a Linux based server, and fails when ran on a Windows based server.

Added:

Method serverOS(): Returns integer, 1 if Windows, 2 if Linux, 3 if other
Field $serverOS: int

On instantiation OS is determined and stored in the object field serverOS. The field is used as a logic check when the run method is called.

**Comment by florianeckerstorfer** [comment]
This breaks compatibility with Mac OS X.

**Comment by Samyoul** [comment]
No problem, I'll just tweak the code.

**Comment by florianeckerstorfer** [comment]
I just realised, a little bit too late, that your code does not support piping the output of a process into a file. Could you add that feature (I have absolutely no idea how to do this on Windows).

Does stopping a process and checking if it's running work?

**Pull request merged**
